backend:
  name: github
  repo: BrianPappalardo/pappalar.do # Path to your Github repository
  branch: master # Branch to update (master by default)

media_folder: "images/uploads" # Folder where user uploaded files should go
public_foler: "/images/uploads" # The src attr for uploaded media will begin with /images/uploads/

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, e.g., /admin/collections/:slug/edit
    label: "Post" # Used in the UI, e.g., "New Post"
    folder: "source/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Subtitle", name: "subtitle", widget: "string"}
      - {label: "Brief Description", name:"brief_description", widget: "markdown"}
      - {label: "Featured Image", name: "featured_image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Foo", name: "foo", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - name: "content_block"
        label: "Content Block"
        widget: "list"
        fields:
          - name: "text_block"
            label: "Text Block"
            widget: "list"
            fields:
              - {label: "Heading", name: "Heading", widget: string, tagname: "h2"}
              - {label: "Copy", name: "copy", widget: markdown}
          - name: "image_block"
            label: "Image Block"
            widget: "list"
            fields:
              - {label: "Image", name: "image", widget: "image"}
              - {label: "Image Alt Tag", name: "image_alt_tag", widget: "string"}

publish_mode: editorial_workflow
